// 待产&母婴用品清单数据
// 适配：浙江省妇保医院 · 预产期 2026-07-02 · 顺产倾向 · 一体化病房 · 月嫂+家人月子 · 母乳尝试+混合
// priority: must=必备⭐ rec=推荐 opt=可选
// tag: 顺=顺产专属 剖=剖腹产专属 夏=夏季注意 一体化=一体化病房提供 院内=省妇保超市可买
// tier: basic=基础款 premium=进阶款

const META = {
  dueDate: '2026-07-02',
  hospital: '浙江省妇保',
  city: '杭州',
  birthSeason: '盛夏 · 梅雨末',
  preference: '顺产倾向 / 一体化病房(待定) / 月嫂+家人 / 母乳尝试+混合',
};

const SCENES = [
  { id: 'doc',           name: '证件包',          icon: '📄', urgency: 'S1', desc: '随身小包，临产前备好' },
  { id: 'delivery',      name: '产房包',          icon: '🏥', urgency: 'S1', desc: '独立手提袋，待产/分娩直接拎进产房' },
  { id: 'companion',     name: '陪护包',          icon: '👨', urgency: 'S2', desc: '爸爸/家属住院 3-5 天' },
  { id: 'hospital_mom',  name: '住院 · 妈妈',     icon: '🤱', urgency: 'S2', desc: '病房 3-5 天用量' },
  { id: 'hospital_baby', name: '住院 · 宝宝',     icon: '👶', urgency: 'S2', desc: '病房 3-5 天用量' },
  { id: 'home_feed',     name: '月子家用 · 喂养', icon: '🍼', urgency: 'S3', desc: '吸奶/储奶/温奶/消毒' },
  { id: 'home_care',     name: '月子家用 · 洗护', icon: '🧴', urgency: 'S3', desc: '洗澡/护肤/洗衣' },
  { id: 'home_sleep',    name: '月子家用 · 睡眠', icon: '🛏️', urgency: 'S3', desc: '床/床品/睡袋/蚊帐' },
  { id: 'home_travel',   name: '月子家用 · 出行', icon: '🚗', urgency: 'S3', desc: '安全座椅/推车' },
  { id: 'home_env',      name: '月子家用 · 环境', icon: '🌡️', urgency: 'S3', desc: '监护/温湿度/空气' },
  { id: 'home_med',      name: '月子家用 · 药品', icon: '💊', urgency: 'S3', desc: '维生素/外用药/工具' },
  { id: 'home_toy',      name: '月子家用 · 玩具', icon: '🎀', urgency: 'S3', desc: '0-3 月早教' },
  { id: 'later',         name: '后续添置 (4m+)',  icon: '📅', urgency: 'S4', desc: '辅食期/爬行期再买' },
];

const ITEMS = [
  // ========== 证件包 ==========
  { id:'doc-id', scene:'doc', name:'夫妻双方身份证', qty:'各 1', priority:'must',
    note:'办出生证、医保登记必备' },
  { id:'doc-hukou', scene:'doc', name:'户口本', qty:'1', priority:'must',
    note:'宝宝落户、办医保用' },
  { id:'doc-marriage', scene:'doc', name:'结婚证', qty:'1', priority:'must' },
  { id:'doc-medicare', scene:'doc', name:'医保卡（妈妈）', qty:'1', priority:'must' },
  { id:'doc-pregbook', scene:'doc', name:'产检本、母子健康手册', qty:'全套', priority:'must',
    note:'全程产检记录，建档时医院发的小册子' },
  { id:'doc-permit', scene:'doc', name:'准生证（电子版即可）', qty:'1', priority:'rec',
    note:'一般用不到，备着' },
  { id:'doc-admission', scene:'doc', name:'住院申请单 / 近期产检报告', qty:'1套', priority:'must',
    note:'B 超、血常规、糖耐量等' },
  { id:'doc-cash', scene:'doc', name:'现金 + 银行卡', qty:'≥ 7000', priority:'must',
    note:'押金、超市备用；一体化病房日均 450+' },
  { id:'doc-pen', scene:'doc', name:'笔 + 记录本', qty:'1', priority:'opt',
    note:'记录喂奶/排便时间，医院也会发表格' },

  // ========== 产房包 ==========
  { id:'del-pad', scene:'delivery', name:'一次性产褥垫 60×90', qty:'10-15 片', priority:'must',
    tag:['顺'],
    brands:[
      {name:'子初', tier:'basic', price:'¥4/片'},
      {name:'十月结晶', tier:'basic', price:'¥4/片'},
      {name:'护力安', tier:'premium', price:'¥6/片'},
    ],
    note:'顺产消耗大；用过有剩余可当家居隔尿垫' },
  { id:'del-diaper', scene:'delivery', name:'纸尿裤 NB 码', qty:'2 片', priority:'must',
    note:'手术室只用 1 片，备 1 片产后用；NB 大袋放陪护包' },
  { id:'del-hat', scene:'delivery', name:'胎帽', qty:'1', priority:'must',
    tag:['一体化'],
    note:'☀ 夏天用一下下就摘；一体化病房会赠送' },
  { id:'del-tissue', scene:'delivery', name:'棉柔巾', qty:'1 包', priority:'must',
    brands:[
      {name:'BBC 小熊巾', tier:'basic', price:'¥10/包', note:'厚大稍粗'},
      {name:'全棉时代', tier:'premium', price:'¥15/包', note:'软但薄小'},
    ] },
  { id:'del-cup', scene:'delivery', name:'吸管保温杯', qty:'1', priority:'must',
    brands:[
      {name:'bablov 316', tier:'basic', price:'¥90'},
      {name:'膳魔师', tier:'premium', price:'¥200+'},
    ],
    note:'夜里要保温的话装 100℃ 开水；建议带吸嘴替换装' },
  { id:'del-snack', scene:'delivery', name:'能量食物（巧克力/红牛/面包/蜂蜜）', qty:'按需', priority:'must',
    tag:['顺','院内'],
    note:'顺产保持体力；剖不用；省妇保超市可买' },
  { id:'del-drink', scene:'delivery', name:'运动饮料（带重力球）', qty:'1-2 瓶', priority:'must',
    tag:['顺','院内'],
    brands:[{name:'尖叫/脉动', tier:'basic', price:'¥6'}],
    note:'躺着喝不洒；剖不用；省妇保超市可买' },
  { id:'del-water', scene:'delivery', name:'矿泉水', qty:'按需', priority:'rec',
    tag:['院内'],
    note:'病房有热水壶，可买一桶兑温水喝' },
  { id:'del-stocking', scene:'delivery', name:'医用弹力袜', qty:'1 双', priority:'must',
    tag:['剖','院内'],
    note:'⚠ 省妇保**统一规格**必须院内买，不要提前在外面买' },
  { id:'del-belt', scene:'delivery', name:'医用束腹带（无弹纱布款）', qty:'1', priority:'must',
    tag:['剖'],
    brands:[{name:'护力安', tier:'basic', price:'¥60-130', note:'紫边/黄边'}],
    note:'剖宫产术后下床用' },
  { id:'del-urinal', scene:'delivery', name:'一次性接尿盆', qty:'1', priority:'must',
    tag:['剖','院内'],
    note:'省妇保统一买' },
  { id:'del-monitor', scene:'delivery', name:'胎心监护带', qty:'2 条', priority:'must',
    brands:[{name:'爱孕加柔版', tier:'basic', price:'¥20/2 条'}],
    note:'孕晚期产检、住院都要用，常带' },
  { id:'del-phone', scene:'delivery', name:'手机 + 充电器（线 ≥1.5m）', qty:'1 套', priority:'must',
    note:'病床插座距离远，短线不够' },
  { id:'del-oxygen', scene:'delivery', name:'氧气瓶（小型便携）', qty:'1 瓶', priority:'opt',
    tag:['顺'],
    brands:[{name:'富林 1L', tier:'basic', price:'¥16/瓶'}],
    note:'顺产中后期氧气支持，看个人需要' },

  // ========== 陪护包 ==========
  { id:'comp-slipper', scene:'companion', name:'陪护拖鞋', qty:'1 双', priority:'must',
    tag:['院内'],
    note:'省妇保超市买（自带的反映难穿）' },
  { id:'comp-towel', scene:'companion', name:'陪护毛巾', qty:'1 条', priority:'must' },
  { id:'comp-wash', scene:'companion', name:'陪护洗漱包 + 刮胡刀 + 护肤', qty:'1 套', priority:'must' },
  { id:'comp-cloth', scene:'companion', name:'陪护换洗衣物（短袖+短裤）', qty:'3-5 套', priority:'must',
    tag:['夏'],
    note:'☀ 杭州 7 月闷热出汗多+梅雨潮湿衣服难干，多备' },
  { id:'comp-blanket', scene:'companion', name:'薄毯', qty:'1', priority:'rec',
    tag:['一体化'],
    note:'一体化提供被枕，可不带；陪护床凉可加' },
  { id:'comp-hanger', scene:'companion', name:'衣架', qty:'3-4 个', priority:'rec',
    tag:['一体化'] },
  { id:'comp-tissue', scene:'companion', name:'抽纸 + 卷纸', qty:'各 1 包', priority:'must',
    tag:['一体化'],
    note:'一体化提供餐巾纸；不愿多带可院内买' },
  { id:'comp-wettissue', scene:'companion', name:'湿厕纸 + 消毒湿巾', qty:'各 1 包', priority:'rec' },
  { id:'comp-utensil', scene:'companion', name:'一次性碗筷勺杯 + 吸管', qty:'1 套（7-10 人份）', priority:'must',
    note:'⚠ 医院不提供餐具；后期省着用' },
  { id:'comp-glove', scene:'companion', name:'一次性手套', qty:'1 包', priority:'rec',
    note:'护工帮换垫单时用' },
  { id:'comp-mask', scene:'companion', name:'成人口罩', qty:'30 只', priority:'must' },
  { id:'comp-nail', scene:'companion', name:'指甲剪（妈妈+爸爸）', qty:'各 1', priority:'rec' },
  { id:'comp-dryer', scene:'companion', name:'电吹风', qty:'1', priority:'opt',
    tag:['一体化'],
    note:'一体化提供电吹风' },
  { id:'comp-bag', scene:'companion', name:'收纳袋 / 脏衣袋', qty:'4-6 个', priority:'rec' },
  { id:'comp-eye', scene:'companion', name:'蒸汽眼罩', qty:'5 片', priority:'opt',
    brands:[{name:'花王 SteamCream', tier:'premium', price:'¥30/5 片'}],
    note:'💡 夜里宝宝哭，眼罩助眠' },
  { id:'comp-fan', scene:'companion', name:'充电小风扇', qty:'1', priority:'rec',
    tag:['夏'],
    brands:[{name:'JISULIFE/小米', tier:'basic', price:'¥80-150'}],
    note:'☀ 产妇怕风但热，定向吹脚或环境通风' },

  // ========== 住院 · 妈妈 ==========
  { id:'hm-hat', scene:'hospital_mom', name:'月子帽（薄棉）', qty:'1', priority:'must',
    tag:['夏'],
    brands:[{name:'爱孕/嫚熙', tier:'basic', price:'¥30'}],
    note:'☀ 选纯棉薄款，否则闷' },
  { id:'hm-band', scene:'hospital_mom', name:'月子发带', qty:'1', priority:'rec',
    brands:[{name:'嫚熙长绒棉刺绣', tier:'basic', price:'¥34'}] },
  { id:'hm-sock', scene:'hospital_mom', name:'月子袜（薄款松口）', qty:'3 双', priority:'must',
    tag:['夏'],
    brands:[{name:'嫚熙夏季薄款', tier:'basic', price:'¥38/3 双'}] },
  { id:'hm-shoe', scene:'hospital_mom', name:'月子鞋', qty:'1 双', priority:'must',
    brands:[
      {name:'十月结晶', tier:'basic', price:'¥37'},
      {name:'防滑拖鞋（院内）', tier:'basic', price:'院内买'},
    ],
    note:'包跟防滑款，月嫂可能也会给' },
  { id:'hm-cloth', scene:'hospital_mom', name:'月子服 / 哺乳衣（前开襟纱布纯棉）', qty:'2-3 套', priority:'must',
    tag:['夏'],
    brands:[
      {name:'未来总裁', tier:'basic', price:'¥150/套'},
      {name:'loveloc 纱布', tier:'premium', price:'¥158/件'},
    ],
    note:'☀ 杭州梅雨潮湿衣服难干，多备 1 套' },
  { id:'hm-bra', scene:'hospital_mom', name:'哺乳文胸', qty:'2-3 件', priority:'must',
    brands:[
      {name:'嫚熙', tier:'basic', price:'¥90/件'},
      {name:'美德乐轻盈款', tier:'premium', price:'¥140/件', note:'薄稍大'},
    ],
    note:'💡 临产前再买（尺寸好确认）；产后还会涨杯，准备小尺码 2 + 大 1 件' },
  { id:'hm-pad', scene:'hospital_mom', name:'防溢乳垫', qty:'12 片起', priority:'must',
    brands:[
      {name:'BBC 超薄', tier:'basic', price:'¥0.6/片'},
      {name:'兰思诺蓝芯', tier:'premium', price:'¥1.5/片'},
    ],
    note:'母乳必备；勤换避免细菌感染，用量大' },
  { id:'hm-nipple', scene:'hospital_mom', name:'乳头膏（羊脂膏）', qty:'1 支', priority:'must',
    brands:[
      {name:'兰思诺', tier:'basic', price:'¥80'},
      {name:'美德乐羊脂膏 2.0', tier:'premium', price:'¥120'},
    ],
    note:'母乳必备，买吸奶器常赠送' },
  { id:'hm-panty', scene:'hospital_mom', name:'一次性内裤', qty:'XL 12 条 [剖] / L 20 条 [顺]', priority:'must',
    brands:[{name:'BBC 中腰', tier:'basic', price:'¥3/条'}],
    note:'剖产建议高腰，术后买大点舒服；顺产 L 即可' },
  { id:'hm-mat1', scene:'hospital_mom', name:'计量型产妇卫生巾', qty:'1 包', priority:'must',
    brands:[
      {name:'开丽计量型', tier:'basic', price:'¥29/3 片', note:'第 1 天用'},
      {name:'子初', tier:'basic', price:'¥40/10 片'},
    ],
    note:'产后第 1 天用，可观察出血量' },
  { id:'hm-mat2', scene:'hospital_mom', name:'夜用卫生巾', qty:'1 包', priority:'must',
    note:'后期换普通卫生巾用' },
  { id:'hm-toilet', scene:'hospital_mom', name:'一次性马桶垫', qty:'12 个', priority:'rec',
    tag:['一体化'],
    brands:[{name:'BBC 全包无纺布', tier:'basic', price:'¥27/30 片'}],
    note:'一体化单人间可不带' },
  { id:'hm-pad60', scene:'hospital_mom', name:'产褥垫 60×90（病房用）', qty:'5-10 片', priority:'must',
    note:'与产房包共用同款；床上垫着接恶露' },
  { id:'hm-tooth', scene:'hospital_mom', name:'月子专用软毛牙刷+牙膏', qty:'1 套', priority:'must',
    brands:[{name:'十月结晶月子牙膏', tier:'basic', price:'¥26/套'}] },
  { id:'hm-mouth', scene:'hospital_mom', name:'孕妇漱口水', qty:'1 瓶', priority:'rec',
    brands:[
      {name:'李施德林冰蓝零度', tier:'basic', price:'¥10'},
      {name:'贝亲孕妇漱口水', tier:'premium', price:'¥40'},
    ],
    note:'月子里可漱口代刷牙' },
  { id:'hm-bowl', scene:'hospital_mom', name:'妈妈毛巾 + 折叠盆（擦身用）', qty:'1+1', priority:'must',
    brands:[{name:'折叠盆 34cm', tier:'basic', price:'¥10'}],
    note:'月子不能淋浴，擦身用' },
  { id:'hm-wash', scene:'hospital_mom', name:'私处清洗器（弯头瓶）', qty:'1', priority:'rec',
    tag:['顺'],
    brands:[{name:'十月结晶 75° 500ml', tier:'basic', price:'¥27'}],
    note:'顺产侧切清洗用；剖产可不带' },
  { id:'hm-cold', scene:'hospital_mom', name:'冷敷垫（侧切/伤口）', qty:'3 片', priority:'rec',
    tag:['顺','剖'],
    brands:[{name:'护力安 COOL30', tier:'basic', price:'¥17/片'}] },
  { id:'hm-waterproof', scene:'hospital_mom', name:'剖宫产防水贴', qty:'5 片', priority:'must',
    tag:['剖'],
    brands:[{name:'贝莱康 4×19', tier:'basic', price:'¥27/5 片'}],
    note:'洗澡防伤口进水' },
  { id:'hm-scar', scene:'hospital_mom', name:'疤痕贴', qty:'2 片', priority:'rec',
    tag:['剖'],
    brands:[
      {name:'仙卡', tier:'basic', price:'¥80/片'},
      {name:'美皮护 3×15', tier:'premium', price:'¥160/片'},
    ],
    note:'拆线后开始用，建议买进阶款，效果区别明显' },
  { id:'hm-painkill', scene:'hospital_mom', name:'双氯芬酸钠栓', qty:'1 盒', priority:'rec',
    tag:['剖'],
    note:'剖产术后镇痛栓' },
  { id:'hm-discharge', scene:'hospital_mom', name:'出院服（薄棉长袖+长裤）', qty:'1 套', priority:'must',
    tag:['夏'],
    note:'☀ 7 月别太厚，避风即可' },

  // ========== 住院 · 宝宝 ==========
  { id:'hb-diaper', scene:'hospital_baby', name:'纸尿裤 NB 码', qty:'约 90 片', priority:'must',
    brands:[
      {name:'好奇柯基', tier:'basic', price:'¥1.2/片'},
      {name:'花王 NB', tier:'basic', price:'¥1.7/片', note:'有反馈厚&坨'},
      {name:'大王自然之恩', tier:'basic', price:'¥2/片', note:'软透气'},
      {name:'帮宝适黑金帮', tier:'premium', price:'¥2.5/片'},
      {name:'BBC 皇室狮子王国', tier:'premium', price:'¥2.5/片', note:'软'},
      {name:'尤妮佳皇室', tier:'premium', price:'¥3/片'},
    ],
    note:'💡 NB 期换得勤只要软就行；多买试用装试 4 片，选适合宝宝身材的' },
  { id:'hb-undermat', scene:'hospital_baby', name:'一次性隔尿垫（小）', qty:'1 包 4 片', priority:'rec',
    note:'换尿不湿垫；月子里也可临时使用' },
  { id:'hb-tissue', scene:'hospital_baby', name:'宝宝棉柔巾', qty:'3 包', priority:'must',
    brands:[
      {name:'BBC 小熊巾', tier:'basic', price:'¥10/包', note:'厚大'},
      {name:'安慕斯', tier:'basic', price:'¥10/包'},
      {name:'全棉时代', tier:'premium', price:'¥15/包', note:'软但薄小'},
    ],
    note:'用量最大，洗屁屁/擦身全靠它' },
  { id:'hb-soft', scene:'hospital_baby', name:'云柔巾（擦脸鼻）', qty:'2 包', priority:'rec',
    brands:[
      {name:'可心柔 V9', tier:'basic', price:'¥5/包'},
      {name:'BBC', tier:'basic', price:'¥6/包'},
    ] },
  { id:'hb-burp', scene:'hospital_baby', name:'拍嗝巾 / 小方巾', qty:'2 条', priority:'must',
    brands:[{name:'nestdesigns 竹棉双层', tier:'premium', price:'¥35/条', note:'越洗越软'}] },
  { id:'hb-spoon', scene:'hospital_baby', name:'硅胶软勺 + 收纳盒', qty:'1 套', priority:'rec',
    brands:[
      {name:'可优比', tier:'basic', price:'¥15'},
      {name:'BBC', tier:'premium', price:'¥25'},
    ],
    note:'喂水奶/果汁；一次性碗也能凑合' },
  { id:'hb-cup', scene:'hospital_baby', name:'硅胶碗（可热水煮）', qty:'1', priority:'opt',
    brands:[{name:'combi 260ml', tier:'premium', price:'¥40'}] },
  { id:'hb-bottle', scene:'hospital_baby', name:'奶瓶 150ml', qty:'1', priority:'must',
    brands:[
      {name:'贝亲 PPSU', tier:'basic', price:'¥80'},
      {name:'hegen PPSU 套装', tier:'premium', price:'¥230 (150+240ml)', note:'★ 直接买套装更省'},
    ],
    note:'💡 母乳喂养可备 0 段奶嘴，避免呛奶；hegen 一套省后续' },
  { id:'hb-brush', scene:'hospital_baby', name:'硅胶奶瓶刷', qty:'1 套', priority:'must',
    brands:[{name:'clevertree 3 件套', tier:'basic', price:'¥21'}] },
  { id:'hb-formula', scene:'hospital_baby', name:'奶粉小罐（1 段，备用）', qty:'1 罐 350g', priority:'must',
    brands:[
      {name:'雀巢能恩全护', tier:'basic', price:'¥160/350g', note:'部分水解，过敏体质可选'},
      {name:'A2 至初', tier:'premium', price:'¥300+'},
      {name:'皇家美素佳儿', tier:'premium', price:'¥400+'},
      {name:'德爱', tier:'premium', price:'¥350+'},
    ],
    note:'💡 省妇保提供启赋水奶；但夜里护士台量杯不够要奶瓶；母乳尝试中先备小罐' },
  { id:'hb-soap', scene:'hospital_baby', name:'婴儿洗衣皂（备用）', qty:'1 块', priority:'opt',
    note:'住院少用；月子中心/家里多用洗衣液' },
  { id:'hb-buttcream', scene:'hospital_baby', name:'护臀霜', qty:'1 瓶', priority:'must',
    brands:[
      {name:'红苹果（院内）', tier:'basic', price:'¥75/50g'},
      {name:'拜耳', tier:'basic', price:'¥80'},
      {name:'Desitin 紫膏', tier:'premium', price:'¥120', note:'红屁股严重用'},
      {name:'Sudocrem', tier:'premium', price:'¥80'},
    ],
    note:'拜耳日常用即可，强效备 Desitin' },
  { id:'hb-grooming', scene:'hospital_baby', name:'指甲剪 + 镊子 + 吸鼻器 + 梳子（4 件套）', qty:'1 套', priority:'must',
    brands:[{name:'贝亲四件套', tier:'basic', price:'¥118'}] },
  { id:'hb-nailfile', scene:'hospital_baby', name:'磨甲片（玻璃锉）', qty:'1', priority:'rec',
    brands:[
      {name:'fasola 玻璃锉', tier:'basic', price:'¥5'},
      {name:'电动磨甲器', tier:'premium', price:'¥60'},
    ] },
  { id:'hb-discharge', scene:'hospital_baby', name:'宝宝出院服 + 薄抱被（120×120 双层纱）', qty:'1 套', priority:'must',
    tag:['夏'],
    brands:[
      {name:'全棉时代水洗纱布 59 码', tier:'basic', price:'¥25/件'},
      {name:'nestdesigns 双层纱大方巾', tier:'premium', price:'¥110/件'},
    ],
    note:'☀ 7 月别用厚抱被，薄纱襁褓即可' },
  { id:'hb-mosquito', scene:'hospital_baby', name:'防蚊贴（备用）', qty:'1 盒', priority:'rec',
    tag:['夏'],
    brands:[{name:'润本叮叮植物精油', tier:'basic', price:'¥10/36 贴'}] },
  { id:'hb-bmask', scene:'hospital_baby', name:'婴儿口罩（备用）', qty:'5 只', priority:'opt',
    note:'住院基本用不上，出院备一些' },

  // ========== 月子家用 · 喂养 ==========
  { id:'feed-pump', scene:'home_feed', name:'电动双边吸奶器', qty:'1', priority:'must',
    brands:[
      {name:'美德乐丝韵翼智能版', tier:'basic', price:'¥1300-1700', note:'★ 经典轻便，含护罩+乳垫+羊脂膏赠品'},
      {name:'贝瑞克大贝贝 Spectra', tier:'premium', price:'¥1500-2000', note:'★ 吸力强能吸后奶，吸得更干净'},
      {name:'Elvie / Willow 穿戴式', tier:'premium', price:'¥3000+', note:'外出/夜间方便'},
    ],
    note:'💡 母乳尝试必备，临产前 1-2 周买；建议先借/二手试用风格' },
  { id:'feed-bag', scene:'home_feed', name:'一次性储奶袋', qty:'100 片起', priority:'must',
    brands:[
      {name:'美德乐（赠送）', tier:'basic', price:'购吸奶器送'},
      {name:'嫚熙', tier:'basic', price:'¥0.5/片'},
      {name:'BBC', tier:'basic', price:'¥0.4/片', note:'稍薄'},
    ] },
  { id:'feed-bottle2', scene:'home_feed', name:'奶瓶 240ml（追加）', qty:'1-2', priority:'rec',
    note:'与住院包 150ml 配套；hegen 套装已含' },
  { id:'feed-warmer', scene:'home_feed', name:'温奶器（带消毒）', qty:'1', priority:'must',
    brands:[
      {name:'小白熊', tier:'basic', price:'¥150'},
      {name:'Bololo', tier:'premium', price:'¥300+'},
    ],
    note:'必备，热奶常用' },
  { id:'feed-sterilizer', scene:'home_feed', name:'紫外线消毒烘干柜（大容量）', qty:'1', priority:'must',
    brands:[
      {name:'太阳公公', tier:'basic', price:'¥300'},
      {name:'大宇', tier:'basic', price:'¥400'},
      {name:'Bololo 18L 豪华款', tier:'premium', price:'¥500+', note:'★ 上+下置 UVC 灯珠，奶瓶+辅食+玩具都能消毒'},
    ],
    note:'高频使用，建议买大' },
  { id:'feed-cleaner', scene:'home_feed', name:'奶瓶清洗剂', qty:'1 瓶', priority:'rec',
    brands:[
      {name:'wickle', tier:'basic', price:'¥30'},
      {name:'贝亲', tier:'basic', price:'¥40'},
      {name:'甘尼克宝贝', tier:'premium', price:'¥80'},
    ],
    note:'💡 部分妈妈担心残留，用热水+消毒替代也可' },
  { id:'feed-pillow', scene:'home_feed', name:'哺乳枕', qty:'1', priority:'rec',
    brands:[
      {name:'良良', tier:'basic', price:'¥100'},
      {name:'美德乐', tier:'premium', price:'¥200+'},
    ] },
  { id:'feed-tea', scene:'home_feed', name:'恒温调奶器', qty:'1', priority:'opt',
    brands:[{name:'小白熊/Bololo', tier:'basic', price:'¥200'}],
    note:'💡 母乳为主可不买；养生壶+保温壶可替代' },

  // ========== 月子家用 · 洗护 ==========
  { id:'care-tub', scene:'home_care', name:'折叠浴盆 + 水温计', qty:'1', priority:'must',
    brands:[
      {name:'okbaby', tier:'basic', price:'¥80'},
      {name:'蒂爱折叠款', tier:'premium', price:'¥140', note:'★ 送水温计'},
      {name:'sttoke', tier:'premium', price:'¥250'},
    ] },
  { id:'care-wash', scene:'home_care', name:'婴儿洗发沐浴二合一', qty:'1', priority:'must',
    brands:[
      {name:'舒适宝', tier:'basic', price:'¥40'},
      {name:'mama&kids', tier:'premium', price:'¥160 (洁肤+洗发)'},
    ] },
  { id:'care-lotion', scene:'home_care', name:'润肤乳 + 面霜', qty:'各 1', priority:'must',
    brands:[
      {name:'mama&kids', tier:'basic', price:'¥250 (乳液+面霜)', note:'稍油'},
      {name:'纽强黄罐 滋润型', tier:'premium', price:'¥250/200g', note:'★ 湿疹预防胜于治疗'},
      {name:'纽强蓝罐 清爽型', tier:'premium', price:'¥250/200g', note:'☀ 夏天用'},
    ],
    note:'☀ 7 月先用蓝罐，秋冬换黄罐' },
  { id:'care-mouthcream', scene:'home_care', name:'口水疹膏（嘴周乳霜）', qty:'1', priority:'must',
    brands:[{name:'mama&kids 嘴周乳霜', tier:'basic', price:'¥115/18g'}],
    note:'口水疹预防胜于治疗，复购很多' },
  { id:'care-oil', scene:'home_care', name:'抚触油', qty:'1', priority:'rec',
    brands:[
      {name:'松达山茶油', tier:'basic', price:'¥30/50ml'},
      {name:'evereden', tier:'premium', price:'¥160/118ml'},
    ],
    note:'💡 用纽强直接抚触也行；头上有乳痂可用油浸润后清水洗' },
  { id:'care-peach', scene:'home_care', name:'桃子水（爽身水）', qty:'1', priority:'must',
    tag:['夏'],
    brands:[{name:'贝亲日版 200ml', tier:'basic', price:'¥59'}],
    note:'☀ 夏天痱子必备' },
  { id:'care-liquid', scene:'home_care', name:'婴儿洗衣液', qty:'1 瓶', priority:'must',
    brands:[
      {name:'BBC 酵素', tier:'basic', price:'¥19/800ml'},
      {name:'attitude 3 倍浓缩', tier:'premium', price:'¥130/1L'},
      {name:'保宁洗衣皂', tier:'basic', price:'¥68/6 块', note:'手洗用'},
    ] },
  { id:'care-washer', scene:'home_care', name:'婴儿洗衣机（带高温煮洗）', qty:'1', priority:'must',
    brands:[
      {name:'美的 mini 3kg 95°', tier:'basic', price:'¥850', note:'★ 高温煮洗除菌'},
      {name:'海尔/小米', tier:'basic', price:'¥800-1000'},
      {name:'大宇带烘干', tier:'premium', price:'¥1500+'},
    ],
    note:'☀ 杭州梅雨衣服难干，强烈推荐带烘干款' },
  { id:'care-hanger-b', scene:'home_care', name:'宝宝小衣架', qty:'20 个', priority:'rec',
    brands:[{name:'婴儿防滑伸缩衣架', tier:'basic', price:'¥26/20 个'}] },
  { id:'care-rack', scene:'home_care', name:'婴儿专用晾衣架', qty:'1', priority:'rec',
    note:'每天要晾的多，单独一个更方便' },
  { id:'care-zinc', scene:'home_care', name:'氧化锌软膏', qty:'1 盒', priority:'must',
    brands:[{name:'药店通用 15% 20g', tier:'basic', price:'¥7'}],
    note:'红屁股神器，便宜大碗' },

  // ========== 月子家用 · 睡眠 ==========
  { id:'sleep-crib', scene:'home_sleep', name:'婴儿床 + 床垫', qty:'1 套', priority:'must',
    brands:[
      {name:'valdera 实木', tier:'basic', price:'¥1000'},
      {name:'faroro 山毛榉 + 空气纤维床垫', tier:'premium', price:'¥1700', note:'★ CoolMax 可水洗外罩'},
    ],
    note:'💡 早点买放阳台散味' },
  { id:'sleep-sheet', scene:'home_sleep', name:'婴儿床笠（夏季纱布款）', qty:'2 套', priority:'must',
    tag:['夏'],
    brands:[
      {name:'纳若思 120×70', tier:'basic', price:'¥60/套'},
      {name:'格里尼/nestdesigns', tier:'premium', price:'¥120/套'},
      {name:'卡迪派凉席', tier:'basic', price:'¥80', note:'☀ 三伏可用'},
    ] },
  { id:'sleep-sack', scene:'home_sleep', name:'薄款投降式睡袋', qty:'2 条', priority:'must',
    tag:['夏'],
    brands:[
      {name:'ergobag 投降袖薄款 M', tier:'basic', price:'¥150', note:'★ 月子里用'},
      {name:'nestdesigns 纱布睡袋', tier:'premium', price:'¥200'},
    ],
    note:'☀ 7 月用襁褓太厚不能用，投降式睡袋是正解' },
  { id:'sleep-swaddle', scene:'home_sleep', name:'防惊跳襁褓（薄款）', qty:'1', priority:'rec',
    tag:['夏'],
    brands:[{name:'ergobag 薄', tier:'basic', price:'¥130'}],
    note:'☀ 选薄款；nestdesigns 厚款 7 月用不上' },
  { id:'sleep-net', scene:'home_sleep', name:'婴儿蚊帐', qty:'1', priority:'must',
    tag:['夏'],
    brands:[{name:'BBC 蒙古包大号 0-4 岁', tier:'basic', price:'¥110', note:'★ 送蚊香液'}],
    note:'☀ 杭州夏天必备' },
  { id:'sleep-pillow', scene:'home_sleep', name:'定型枕（可选）', qty:'1', priority:'opt',
    brands:[{name:'evoceler CoolMax', tier:'basic', price:'¥80'}],
    note:'💡 大部分宝宝自己睡圆回来，效果一般' },
  { id:'sleep-comfort', scene:'home_sleep', name:'安抚枕 / 糖果枕', qty:'1', priority:'opt',
    brands:[
      {name:'BBC 糖果枕', tier:'basic', price:'¥60'},
      {name:'爱孕月亮安抚枕', tier:'premium', price:'¥60'},
    ],
    note:'小月龄两边夹一下有安全感' },
  { id:'sleep-mompillow', scene:'home_sleep', name:'孕妇枕 / 哺乳枕', qty:'1', priority:'rec',
    brands:[{name:'爱孕 U 型 CoolMax', tier:'premium', price:'¥479', note:'排湿速干'}],
    note:'孕晚期到产后哺乳都用得到，长条枕后续给宝宝爬爬' },

  // ========== 月子家用 · 出行 ==========
  { id:'travel-seat', scene:'home_travel', name:'安全座椅（0-7 岁旋转款）', qty:'1', priority:'must',
    brands:[
      {name:'惠尔顿智转 pro', tier:'basic', price:'¥1800'},
      {name:'savile 猫头鹰妙转 pro', tier:'premium', price:'¥2300', note:'★ 360 旋转，云台式'},
    ],
    note:'⚠ 出院当天就要用！预产期前 2 周买好装好' },
  { id:'travel-stroller', scene:'home_travel', name:'婴儿推车', qty:'1', priority:'must',
    brands:[
      {name:'pouch 巨能装/伞车', tier:'basic', price:'¥500-800'},
      {name:'stokke Xplory', tier:'premium', price:'¥6000+'},
      {name:'cybex Mios/Priam', tier:'premium', price:'¥4000-6000'},
    ],
    note:'💡 可以问朋友继承；夏天选高景观+遮阳好的' },
  { id:'travel-carrier', scene:'home_travel', name:'婴儿背带 / 腰凳', qty:'1', priority:'rec',
    brands:[
      {name:'四季 mami', tier:'basic', price:'¥200'},
      {name:'Ergobaby / Babybjorn', tier:'premium', price:'¥1000+'},
    ],
    note:'4-6 个月颈部稳后用' },
  { id:'travel-rocker', scene:'home_travel', name:'婴儿摇椅 / 哄睡神器', qty:'1', priority:'opt',
    brands:[
      {name:'mamaroo 4', tier:'premium', price:'¥3000'},
      {name:'nuna leaf', tier:'premium', price:'¥2500'},
    ],
    note:'💡 可向朋友继承' },

  // ========== 月子家用 · 环境 ==========
  { id:'env-monitor', scene:'home_env', name:'AI 智能婴儿监护器', qty:'1', priority:'must',
    brands:[
      {name:'海马爸比 pro AI', tier:'premium', price:'¥360', note:'★ 防呛奶/睡姿监测'},
      {name:'cubo ai', tier:'premium', price:'¥1000+'},
    ] },
  { id:'env-thermo', scene:'home_env', name:'电子温湿度计', qty:'2', priority:'must',
    tag:['夏'],
    brands:[
      {name:'德力西夜光款', tier:'basic', price:'¥40'},
      {name:'米家蓝牙温湿度计', tier:'basic', price:'¥60', note:'手机看数据'},
    ],
    note:'☀ 卧室+客厅各 1，空调房 26°/湿度 50-60% 最佳' },
  { id:'env-humidifier', scene:'home_env', name:'加湿器', qty:'1', priority:'must',
    tag:['夏'],
    brands:[
      {name:'小米/米家智能', tier:'basic', price:'¥250'},
      {name:'戴森 PH04', tier:'premium', price:'¥4500+', note:'带净化+加湿'},
      {name:'舒乐氏 RO 上加水', tier:'premium', price:'¥1500+'},
    ],
    note:'☀ 空调房湿度易低于 40%，影响宝宝呼吸道；建议无雾型/上加水款' },
  { id:'env-purifier', scene:'home_env', name:'空气净化器（HEPA）', qty:'1', priority:'rec',
    brands:[
      {name:'米家空气净化器 4', tier:'basic', price:'¥1000'},
      {name:'IQAir HealthPro', tier:'premium', price:'¥10000+'},
      {name:'Blueair 7440i', tier:'premium', price:'¥4000+'},
    ],
    note:'☀ 杭州雨季霉菌+空调房通风差；选 CADR ≥ 400 款' },
  { id:'env-ear', scene:'home_env', name:'耳温枪', qty:'1', priority:'must',
    brands:[
      {name:'欧姆龙 MC-682', tier:'basic', price:'¥250'},
      {name:'博朗 IRT', tier:'premium', price:'¥400', note:'可走医保历年账户'},
    ] },
  { id:'env-light', scene:'home_env', name:'小夜灯（暖光）', qty:'1', priority:'opt',
    note:'💡 多数时候建议保持黑暗利于宝宝建立昼夜节律，少用' },
  { id:'env-table', scene:'home_env', name:'尿布台', qty:'1', priority:'must',
    brands:[
      {name:'可优比', tier:'basic', price:'¥300'},
      {name:'豆巴米 山毛榉实木常规款', tier:'premium', price:'¥500', note:'★ 大，实木，可做柜子用'},
    ],
    note:'💡 高频使用，强烈推荐进阶款' },
  { id:'env-undermat', scene:'home_env', name:'可水洗隔尿垫', qty:'2 条', priority:'must',
    brands:[
      {name:'cutelife 70×90', tier:'basic', price:'¥86'},
      {name:'littletiny outlast', tier:'premium', price:'¥110'},
    ],
    note:'尿布台/床上用' },
  { id:'env-undermat2', scene:'home_env', name:'一次性隔尿垫（中号）', qty:'1-2 包', priority:'rec',
    brands:[{name:'德佑银装 33×45', tier:'basic', price:'¥25/46 片'}],
    note:'外出/晾屁股用' },

  // ========== 月子家用 · 药品 ==========
  { id:'med-d3', scene:'home_med', name:'维生素 D3', qty:'1 瓶', priority:'must',
    brands:[
      {name:'星鲨（省妇保会开）', tier:'basic', price:'¥30', note:'出生 8 天后吃'},
      {name:'Ddrops 400IU', tier:'premium', price:'¥87/90 滴', note:'★ 每日 1 滴，无味'},
      {name:'伊可新 AD', tier:'basic', price:'¥40', note:'省妇保也会开'},
    ],
    note:'💡 省妇保先开星鲨/伊可新交替；后续可换 Ddrops' },
  { id:'med-eye', scene:'home_med', name:'红霉素眼膏', qty:'1 支', priority:'rec',
    brands:[{name:'药店通用 10g', tier:'basic', price:'¥3'}],
    note:'破溃备用；妈妈乳头破也能用（喂奶前洗掉）' },
  { id:'med-papaw', scene:'home_med', name:'木瓜膏', qty:'1', priority:'rec',
    brands:[{name:'Lucas Papaw 25g', tier:'basic', price:'¥20/支'}],
    note:'脸上抓伤、长包、小擦伤通用' },
  { id:'med-bug', scene:'home_med', name:'蚊虫叮咬膏', qty:'1', priority:'must',
    tag:['夏'],
    brands:[{name:'宝弘 boiron 金盏花软膏', tier:'premium', price:'¥51', note:'温和不刺激'}],
    note:'☀ 夏天必备；大人小孩通用' },
  { id:'med-thermo', scene:'home_med', name:'体温计（备用）', qty:'1', priority:'rec',
    note:'有耳温枪就够；月子里月嫂可能会要求每天测' },

  // ========== 月子家用 · 玩具 ==========
  { id:'toy-bw', scene:'home_toy', name:'黑白卡', qty:'1 套', priority:'rec',
    brands:[{name:'中信出版社 0-2 岁', tier:'basic', price:'¥55'}],
    note:'💡 月子里别看太久，1-3 个月用得多' },
  { id:'toy-rattle', scene:'home_toy', name:'沙锤 / 摇铃', qty:'1', priority:'rec',
    brands:[
      {name:'BBC 抓握玩具双头沙球', tier:'basic', price:'¥25'},
      {name:'面包超人', tier:'premium', price:'¥80'},
    ] },
  { id:'toy-gym', scene:'home_toy', name:'健身架', qty:'1', priority:'must',
    brands:[
      {name:'宜家雷卡', tier:'basic', price:'¥150', note:'★ 经典款，宝宝接受度高'},
      {name:'费雪豪华版', tier:'premium', price:'¥600'},
    ] },
  { id:'toy-comfort', scene:'home_toy', name:'安抚海马 / 安抚巾', qty:'1', priority:'opt',
    brands:[
      {name:'费雪海马', tier:'basic', price:'¥150'},
      {name:'jellycat 小动物', tier:'premium', price:'¥300+'},
      {name:'kaloo', tier:'premium', price:'¥250'},
    ],
    note:'💡 海马爸比监护器赠送小海马可凑合' },
  { id:'toy-cloth', scene:'home_toy', name:'布书 / 触摸书', qty:'2 本', priority:'opt',
    brands:[
      {name:'jollybaby', tier:'basic', price:'¥25/本'},
      {name:'小鸡球球触感书', tier:'premium', price:'¥80/5 册'},
    ],
    note:'2-3 月开始抓握' },

  // ========== 后续添置 (4m+) ==========
  { id:'later-teether', scene:'later', name:'牙胶（4-6m）', qty:'1-2', priority:'rec',
    brands:[
      {name:'妈贝乐', tier:'basic', price:'¥30'},
      {name:'火柴猴 Matchstick Monkey', tier:'premium', price:'¥115'},
      {name:'mushie/moyuun', tier:'premium', price:'¥100+'},
    ],
    note:'用一段时间会腻，换着用' },
  { id:'later-bowl', scene:'later', name:'辅食碗勺套装（5-6m）', qty:'1 套', priority:'rec',
    brands:[
      {name:'BBC 吸盘碗', tier:'basic', price:'¥60'},
      {name:'combi 防滑碗', tier:'premium', price:'¥120'},
    ] },
  { id:'later-chair', scene:'later', name:'餐椅（5-6m）', qty:'1', priority:'rec',
    brands:[
      {name:'宜家 Antilop', tier:'basic', price:'¥80', note:'★ 经济实用'},
      {name:'Stokke Tripp Trapp', tier:'premium', price:'¥3000'},
    ] },
  { id:'later-rice', scene:'later', name:'营养米粉（5-6m）', qty:'1 罐', priority:'rec',
    brands:[
      {name:'爱思贝', tier:'basic', price:'¥60'},
      {name:'小皮 / 贝拉米', tier:'premium', price:'¥100+'},
    ],
    note:'2-3 个月吃完一罐，不用囤' },
  { id:'later-mat', scene:'later', name:'爬爬垫 + 围栏（6m）', qty:'1 套', priority:'must',
    brands:[
      {name:'曼龙 5 段无缝 4cm', tier:'basic', price:'¥500'},
      {name:'parklon XPE', tier:'premium', price:'¥1500'},
    ] },
  { id:'later-puree', scene:'later', name:'辅食机 / 蒸煮搅拌一体机', qty:'1', priority:'rec',
    brands:[
      {name:'倍尔嘉/小白熊', tier:'basic', price:'¥300'},
      {name:'beaba', tier:'premium', price:'¥1500+'},
    ] },
  { id:'later-safety', scene:'later', name:'安全防护套装（插座/边角/柜门锁）', qty:'1 套', priority:'must',
    note:'7-8 月会爬后赶紧装，边角防撞棉宝宝会啃，要选硅胶款' },
  { id:'later-cup', scene:'later', name:'学饮杯（鸭嘴/吸管）', qty:'1', priority:'rec',
    brands:[
      {name:'b.box', tier:'basic', price:'¥100'},
      {name:'thinkbaby', tier:'premium', price:'¥200'},
    ] },
  { id:'later-bib', scene:'later', name:'硅胶围兜', qty:'2-3', priority:'rec',
    brands:[
      {name:'BBC', tier:'basic', price:'¥50'},
      {name:'mushie / ezpz', tier:'premium', price:'¥120'},
    ] },
  { id:'later-shears', scene:'later', name:'辅食剪', qty:'1', priority:'rec' },
  { id:'later-bag', scene:'later', name:'滑锁密封食品袋', qty:'1 套', priority:'rec',
    brands:[{name:'茶花拉链密封袋', tier:'basic', price:'¥28/3 盒'}] },
];

// 高配大类（标在大件 item 上 — 用户勾选某类后自动给这些 item 推荐进阶款）
const HC_MAP = {
  // 出行安全
  'travel-seat':'travel', 'travel-stroller':'travel', 'travel-carrier':'travel', 'travel-rocker':'travel',
  // 喂养工具
  'feed-pump':'feed', 'feed-warmer':'feed', 'feed-sterilizer':'feed', 'feed-pillow':'feed',
  'feed-tea':'feed', 'feed-bottle2':'feed', 'hb-bottle':'feed',
  // 睡眠/环境
  'sleep-crib':'sleep', 'sleep-sack':'sleep', 'sleep-swaddle':'sleep', 'sleep-net':'sleep',
  'sleep-sheet':'sleep', 'sleep-mompillow':'sleep',
  'env-humidifier':'sleep', 'env-purifier':'sleep',
  // 监护/护肤
  'env-monitor':'monitor', 'env-ear':'monitor',
  'care-lotion':'monitor', 'care-mouthcream':'monitor',
};

// 品牌产地判定（按 name 子串匹配，先匹配 GLOBAL 后匹配 CN）
const BRAND_ORIGIN_GLOBAL = ['美德乐','medela','贝瑞克','spectra','elvie','willow','momcozy','hegen','贝亲','pigeon',
  '可么多么','comotomo','nuk','花王','大王','帮宝适','好奇','尤妮佳','露安适','兰思诺','mama&kids','mamakids',
  '纽强','mustela','aveeno','evereden','维蕾德','lucas papaw','ddrops','拜耳','desitin','sudocrem',
  'nestdesigns','aden','littletiny','hoppetta','milkbarn','petitbateau','jellycat','kaloo','费雪','fisher',
  'cubo','nanit','owlet','戴森','dyson','blueair','iqair','欧姆龙','omron','博朗','braun','okbaby','sttoke',
  '美皮护','dr kegel','3m','芭克','宜家','ikea','antilop','stokke','tripp','cybex','bugaboo','quinny','joie',
  '巧儿宜','britax','宝得适','nuna','mamaroo','nuna leaf','beaba','b.box','thinkbaby','ezpz','mushie','moyuun',
  'matchstick','火柴猴','bibs','ikv','soothie','面包超人','大宇','smartcare','太阳公公','moony','安兒樂',
  '西门子','siemens','松下','panasonic','博世','bosch','lg','三星','samsung','宝弘','boiron','combi','tucks',
  'dermoplast','earth mama','clevertree','baby k\'tan','quinney','litaf','spectra','goon','sebamed','施巴',
  '雀巢','a2','皇家美素佳儿','德爱','启赋','aptamil','爱他美','holle','tippee','保宁','attitude','wickle',
  '甘尼克','litaf','aqpa','papa','silvercross','avova','bebebus','plantatoy','aden+anais'];

const BRAND_ORIGIN_CN = ['bbc','babycare','子初','十月结晶','护力安','嫚熙','爱孕','开丽','美的','海尔','小米',
  '米家','小白熊','bololo','faroro','纳若思','格里尼','卡迪派','婧麒','evoceler','惠尔顿','savile','猫头鹰',
  'pouch','可优比','豆巴米','海马爸比','舒乐氏','德力西','得力','舒适宝','可心柔','全棉时代','安慕斯','德佑',
  '妈贝乐','中信出版社','jollybaby','小鸡球球','曼龙','蒂爱','贝莱康','可孚','保宁','宝优妮','cainz','小天鹅',
  '卡萨帝','安儿乐','白贝壳','好孩子','goodbaby','valdera','瓦德拉','松达','星鲨','伊可新','红苹果','仙卡',
  'cutelife','米乐鱼','良良','戴可思','启初','红色小象','洁宝','开丽','清漫','奥克斯','森田','bablov',
  'bbc皇室','bbc狮子王国','bbc熊猫','bbc花苞','sannuo','三诺'];

function brandOrigin(name){
  const n = (name || '').toLowerCase();
  for (const k of BRAND_ORIGIN_GLOBAL) if (n.includes(k)) return 'global';
  for (const k of BRAND_ORIGIN_CN) if (n.includes(k)) return 'cn';
  return 'unknown';
}

// 默认偏好
const PROFILE_DEFAULT = {
  budget: 'mid',       // tight | mid | high | top
  style: 'value',      // practical | value | quality | key
  origin: 'either',    // cn | global | either
  highConfig: ['feed','sleep'],  // travel | feed | sleep | monitor
};

if (typeof module !== 'undefined') module.exports = { META, SCENES, ITEMS, HC_MAP, brandOrigin, PROFILE_DEFAULT };
